const badgeStyles = [
	{ name: 'ReactJs', style: 'bg-blue-400 text-blue-800' },
	{ name: 'WebGL', style: 'bg-green-400 text-green-800' },
	{ name: 'Threejs', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'Unity', style: 'bg-red-400 text-red-800' },
	{ name: 'AR/VR', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'DeepLearning', style: 'bg-blue-400 text-blue-800' },
	{ name: 'NeuralNetworks', style: 'bg-green-400 text-green-800' },
	{ name: 'ImageProcessing', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'NaturalLanguageProcessing', style: 'bg-red-400 text-red-800' },
	{ name: 'Tensorflow', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'OpenCV', style: 'bg-purple-400 text-purple-800' },
	{ name: 'Javascript', style: 'bg-blue-400 text-blue-800' },
	{ name: 'Python', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'Java', style: 'bg-red-400 text-red-800' },
	{ name: 'Data-science', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'flutter', style: 'bg-purple-400 text-purple-800' },
	{ name: 'HTML', style: 'bg-blue-400 text-blue-800' },
	{ name: 'CSS', style: 'bg-green-400 text-green-800' },
	{ name: 'Bootstrap', style: 'bg-red-400 text-red-800' },
	{ name: 'WebSocket', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'jQuery', style: 'bg-purple-400 text-purple-800' },
	{ name: 'PHP', style: 'bg-blue-400 text-blue-800' },
	{ name: 'MySQL', style: 'bg-green-400 text-green-800' },
	{ name: 'Pythonframeworrk', style: 'bg-blue-400 text-blue-800' },
	{ name: 'Typescript', style: 'bg-green-400 text-green-800' },
	{ name: 'Tailwind', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'Kotlin', style: 'bg-red-400 text-red-800' },
	{ name: 'JetpackCompose', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'Tkinter', style: 'bg-purple-400 text-purple-800' },
	{ name: 'MongoDB', style: 'bg-blue-400 text-blue-800' },
	{ name: 'SQL', style: 'bg-green-400 text-green-800' },
	{ name: 'Flask', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'Django', style: 'bg-red-400 text-red-800' },
	{ name: 'SCSS', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'GitHubAPI', style: 'bg-purple-400 text-purple-800' },
	{ name: 'Figma', style: 'bg-blue-400 text-blue-800' },
	{ name: 'NextJS14', style: 'bg-green-400 text-green-800' },
	{ name: 'TailwindCSS', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'GSAP', style: 'bg-red-400 text-red-800' },
	{ name: 'Framer-motion', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'NodeJS', style: 'bg-purple-400 text-purple-800' },
	{ name: 'ExpressJS', style: 'bg-blue-400 text-blue-800' },
	{ name: 'GenAI', style: 'bg-green-400 text-green-800' },
	{ name: 'WebSocket', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'ReactJS', style: 'bg-red-400 text-red-800' },
	{ name: 'Redux', style: 'bg-indigo-400 text-indigo-800' },
	{ name: 'MaterialUI', style: 'bg-purple-400 text-purple-800' },
	{ name: 'MERNSTACK(Mongodb,Express.js,React.js,Node.js)', style: 'bg-blue-400 text-blue-800' },
	{ name: 'Postgres', style: 'bg-yellow-400 text-yellow-800' },
	{ name: 'Sequelize', style: 'bg-purple-400 text-purple-800' },
	{ name: 'Redux', style: 'bg-green-400 text-green-800' },
];

export {
	badgeStyles
}
